apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: supabase

resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - secret.yaml

configMapGenerator:
  - name: postgres-init-scripts
    files:
      - 01-schema.sql=init-scripts/01-schema.sql
