apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: supabase-postgres
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/PierreOudin/kubernetes-supabase-test.git
    targetRevision: HEAD
    path: k8s/postgres
  destination:
    server: https://kubernetes.default.svc
    namespace: supabase
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
